Hackdays15/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from webpage.views import *
from webpage.models import *

admin.site.register(Ressort)
admin.site.register(Article)
admin.site.register(Category)
admin.site.register(Description)

base_name = "essenz"

urlpatterns = [
    url(r'^{}/admin/'.format(base_name), include(admin.site.urls)),
    url(r'^{}/$'.format(base_name), HomeView.as_view(), name="landing"),
    url(r'^{}/contact/$'.format(base_name), AboutUsView.as_view(), name="aboutus"),
    url(r'^{}/lexikon/$'.format(base_name), CategoryBaseView.as_view(), name="lexikon_base"),
    url(r'^{}/lexikon/(?P<slug>[^/]+)/$'.format(base_name), CategoryDetailView.as_view(), name="lexikon"),
    url(r'^{}/desc/(?P<slug>[^/]+)/$'.format(base_name), DescDetailView.as_view(), name="desc_detail"),
    url(r'^{}/(?P<slug>[^/]+)/$'.format(base_name), RessortDetailView.as_view(), name="ressort"),
    url(r'^{}/(?P<ressort>[^/]+)/(?P<slug>.+)/$'.format(base_name), ArticleDetailView.as_view(), name="article"),
]

webpage/models.py
# coding=utf-8
import json

from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, editable=False)

    parent = models.ForeignKey('self', null=True, default=None, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

    def get_all_children(self, include_self=True):
        r = []
        if include_self:
            r.append(self)
        for c in Category.objects.filter(parent=self):
            r = r + c.get_all_children(include_self=True)
        return r

    def has_descs(self):
        if len(self.description_set.all()) != 0:
            return True
        else:
            return False

    def get_parents(self):
        r = [self]
        if self.parent:
            r += self.parent.get_parents()
        return r

    def __unicode__(self):
        return self.name


class Ressort(models.Model):
    name = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Ressort, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Article(models.Model):
    ressort = models.ForeignKey(Ressort)
    category = models.ForeignKey(Category, blank=True, null=True)
    author = models.CharField(max_length=50, null=True)

    title = models.CharField('Titel', max_length=100)
    subtitle = models.TextField('Untertitel', null=True, blank=True)

    specialwords = models.TextField('Spezialwörter', null=True, blank=True)
    raw_body = models.TextField()
    body = models.TextField('Inhalt', editable=False)
    created = models.DateTimeField(editable=False)

    slug = models.SlugField(max_length=80, editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()

        super(Article, self).save(*args, **kwargs)

        pars = []
        specwords = []
        for par_index, par in enumerate(self.raw_body.split("\r\n\r\n")):
            for word in par.split(" "):
                if len(word) > 4:
                    if word[-2:] == "$$" and word[:2] == "$$":
                        word = word[2:-2]
                        if word not in specwords:
                            specwords.append(word)
                pars.append(word.strip())

            if par_index != len(self.raw_body.split("\r\n\r\n")):
                pars.append("<br>")

        title = []
        for word in self.title.split(" "):
            if len(word) > 4:
                if word[-2:] == "$$" and word[:2] == "$$":
                    word = word[2:-2]
                    if word not in specwords:
                        specwords.append(word)
            title.append(word)

        self.body = json.dumps(pars)
        self.specialwords = json.dumps(specwords)

        self.title = " ".join(title)

        self.slug = "{}/{}".format(self.id, slugify(self.title))
        return super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ('created',)

    def get_body(self):
        return json.loads(self.body)

    def get_specwords(self):
        return json.loads(self.specialwords)

    def get_teaser(self):
        return json.loads(self.body)[0:30] + ["..."]

    def get_descs(self):
        sluglist = [slugify(word) for word in self.get_specwords()]
        for slug in self.get_specwords():
            print{slug}
        return Description.objects.filter(slug__in=sluglist)

    def __unicode__(self):
        return self.title


class Description(models.Model):
    name = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField(max_length=50, editable=False)

    category = models.ForeignKey(Category, null=True, default=None)
    articles = models.ManyToManyField(Article, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Description, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

webpage/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView, ListView, DetailView
from webpage.models import *


class HomeView(ListView):
    model = Article
    context_object_name = "article_list"
    template_name = "landing.html"
    # paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['article_list'] = Article.objects.exclude(ressort=Ressort.objects.filter(slug="schwerpunkt"))
        context['schwerpunkt_list'] = Article.objects.filter(ressort=Ressort.objects.filter(slug="schwerpunkt"))
        return context


class RessortDetailView(DetailView):
    context_object_name = "ressort"
    template_name = "ressort.html"
    model = Ressort

    # def get_context_data(self, **kwargs):
    #     context = super(RessortDetailView, self).get_context_data(**kwargs)
    #     return context


class ArticleDetailView(DetailView):
    context_object_name = "article"
    template_name = "article.html"
    model = Article

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['text'] = self.object.get_body()
        context['specwords'] = self.object.get_specwords()
        context['descs'] = Description.objects.all()
        return context


class AboutUsView(TemplateView):
    template_name = "aboutus.html"


class CategoryBaseView(ListView):
    model = Category
    template_name = "cat_base.html"
    context_object_name = "category_list"


class CategoryDetailView(DetailView):
    model = Category
    template_name = "cat_detail.html"
    context_object_name = "cat"

    # def get_context_data(self, **kwargs):
    #     context = super(LexikonListView, self).get_context_data(**kwargs)
    #     context['text'] = self.object.get_body()
    #     context['specwords'] = self.object.get_specwords()
    #     return context


class DescDetailView(DetailView):
    model = Description
    template_name = "desc_detail.html"
    context_object_name = "desc"

    # def get_context_data(self, **kwargs):
    #     context = super(LexikonListView, self).get_context_data(**kwargs)
    #     context['text'] = self.object.get_body()
    #     context['specwords'] = self.object.get_specwords()
    #     return context

templates/aboutus.html
{% extends "base.html" %}

{% block header %}
    <header class="sb-page-header">
        <div class="container">
            <h1>Essenz</h1>

            <p>Wer und was sind wir?</p>
        </div>
    </header>
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#        <h1>TROLOLO</h1>#}
    {#    </div>#}
{% endblock %}

{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Das Team</h2>
        </div>

        <div class="col-lg-4 col-sm-6 text-center">
            <img class="img-circle img-responsive img-center" src="{% static 'img/karina.jpg' %}" alt="">

            <h3>Karina Auer
                <small>Journalistin</small>
            </h3>
            <p>Publizistik, Uni Wien</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center">
            <img class="img-circle img-responsive img-center" src="{% static 'img/asura_bw.jpg' %}" alt="">

            <h3>Asura Enkhbayar
                <small>Programmierer</small>
            </h3>
            <p>Cognitive Science, Uni Wien</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center">
            <img class="img-circle img-responsive img-center" src="{% static 'img/iri.jpg' %}" alt="">

            <h3>Irina Pöschl
                <small>Journalistin</small>
            </h3>
            <p>Publizistik, Uni Wien</p>
        </div>
    </div>
{% endblock %}

templates/article.html
{% extends "base.html" %}

{% block title %}
    {{ article.ressort.name }}
{% endblock %}

{% block header %}
    <header class="sb-page-header">
        <div class="container">
            <h1>Essenz</h1>

            <p>{{ article.ressort.name }}</p>
        </div>

    </header>
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#    </div>#}
{% endblock %}

{% block content %}
    {#    <div class="container">#}
    {#        <h1> {{ article.title }} </h1>#}
    {##}
    {#        <h3>{{ article.author }} - {{ article.created }}</h3>#}
    {##}
    {#        <p>#}
    {#            {% for word in article.get_body %}#}
    {#                {% if word == "<br>" %}#}
    {#                    </p><p>#}
    {#                {% elif word in article.get_specwords %}#}
    {#                    <b>{{ word }}</b>#}
    {#                {% else %}#}
    {#                    {{ word }}#}
    {#                {% endif %}#}
    {#            {% endfor %}#}
    {#            </p>#}
    {#    </div>#}

    <div class="row">
        <div class="col-md-12">
            <h2> {{ article.title }} </h2>

            <h4>{{ article.author }} - {{ article.created }}</h4>

            <div class="row">
                <div class="col-md-7">
                    {#                    <h2> {{ article.title }} </h2>#}
                    {##}
                    {#                    <h3>{{ article.author }} - {{ article.created }}</h3>#}

                    <p class="text-justify">
                        {% for word in article.get_body %}
                            {% if word == "<br>" %}
                                </p><p class="text-justify">
                            {% elif word in article.get_specwords %}
                                {% for desc in article.get_descs %}
                                    {% if desc.name == word %}
                                        <b><a href={% url 'desc_detail' desc.slug %}>{{ desc }}</a></b>
                                    {% endif %}
                                {% endfor %}

                            {% else %}
                                {{ word }}
                            {% endif %}
                        {% endfor %}
                        </p>
                </div>
                <div class="col-md-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1 class="panel-title">Was ist was?</h1>
                        </div>
                        <div class="panel-body">
                            <dl class="dl-horizontal">
                                {% for desc in article.get_descs %}
                                    <dt>
                                        <a href={% url 'desc_detail' desc.slug %}>{{ desc.name }}</a>
                                    </dt>
                                    <dd>
                                        {{ desc.body }}
                                    </dd>
                                {% endfor %}
                            </dl>
                        </div>
                    </div>
                </div>
                {#                <p class="text-justify">#}
                {#                    {% for word in article.get_body %}#}
                {#                        {% if word == "<br>" %}#}
                {#                            </p><p class="text-justify">#}
                {#                        {% elif word in article.get_specwords %}#}
                {#                            <b>{{ word }}</b>#}
                {#                        {% else %}#}
                {#                            {{ word }}#}
                {#                        {% endif %}#}
                {#                    {% endfor %}#}
                {#                    </p>#}
            </div>
        </div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400italic,700italic,400,700" rel="stylesheet"
          type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">

    {# Load CSS and JavaScript #}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">

    <!-- Start Bootstrap Custom CSS -->
    <link href="{% static 'css/startbootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/mycustomstyle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/round-about.css' %}" rel="stylesheet" type="text/css">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"
            integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ=="
            crossorigin="anonymous"></script>
</head>

<body>

{% include "navbar.html" %}

{% block header %} {% endblock %}

{# Load the tag library #}
{#{% load bootstrap3 %}#}


<div class="container">
    {% block jumbotron %} {% endblock %}
</div>

<div class="container">
    {% block content %}{% endblock %}
</div>

<div class="container">
    <hr>
    <footer>
        <p>&copy; Team Uni Wien - Hackdays 2015</p>
    </footer>
</div>


<!-- /container -->


{#    {% bootstrap_jquery_url %}#}
{#    {% bootstrap_css %}#}
{#    {% bootstrap_javascript %}#}
</body>
</html>

templates/cat_base.html
{% extends "base.html" %}

{% block header %}
    {% include 'wasistwas_header.html' %}
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#        <h1>TROLOLO</h1>#}
    {#    </div>#}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
    </ol>

    <div class="row">
        <div class="col-md-7">
            {% for overcat in category_list %}
                {% if overcat.parent == None %}
                        <h2><a href={% url 'lexikon' overcat.slug %}>{{ overcat.name }}</a></h2>
                    <div class="list-group">
                        {% for cat in overcat.get_all_children %}
                            {% for desc in cat.description_set.all %}
                                <li class="list-group-item"><a href={% url 'desc_detail' desc.slug %}>{{ desc.name }}</a></li>
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% else %}
                    <h5>{{ cat.name }}</h5>
                {% endif %}
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="/cars?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="/cars?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/cat_detail.html
{% extends "base.html" %}

{% block header %}
    {% include 'wasistwas_header.html' %}
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#        <h1>TROLOLO</h1>#}
    {#    </div>#}
{% endblock %}

{% load static %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href={% url "lexikon_base" %}>Home</a></li>
        {% for subcat in cat.get_parents reversed %}
            <li>
                <a href={% url 'lexikon' subcat.slug %}>
                    {{ subcat.name }}
                </a>
            </li>
        {% endfor %}
    </ol>

    <div class="row">
        <div class="col-md-7">
            {% for overcat in cat.get_all_children %}
                {% if overcat.parent != None %}
                        <h2><a href={% url 'lexikon' overcat.slug %}>{{ overcat.name }}</a></h2></h2>
                        <div class="list-group">
                            {% if overcat.has_descs == True %}
                                {% for desc in overcat.description_set.all %}
                                    <li class="list-group-item"><a
                                            href={% url 'desc_detail' desc.slug %}>{{ desc.name }}</a></li>
                                {% endfor %}
                            {% else %}
                                <li class="list-group-item">Keine Schlagwörter.</li>
                            {% endif %}
                        </div>
                {% endif %}
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="/cars?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="/cars?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
{% endblock %}

templates/desc_detail.html
{% extends "base.html" %}

{% block header %}
    {% include 'wasistwas_header.html' %}
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#        <h1>TROLOLO</h1>#}
    {#    </div>#}
{% endblock %}

{% load static %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href={% url "lexikon_base" %}>Home</a></li>
        {% for subcat in desc.category.get_parents reversed %}
            <li>
                <a href={% url 'lexikon' subcat.slug %}>
                    {{ subcat.name }}
                </a>
            </li>
        {% endfor %}
    </ol>

    <div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">{{ desc.name }}</h1>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    {{ desc.body }}
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-7">
        <hr>
    </div>

    <div class="col-md-7">
        <h2>Kommt vor in:</h2>
        {% for article in desc.articles.all %}
            <h3><a href={% url 'article' article.ressort article.slug %}>
                {{ article.title }}
            </a></h3>
            <h5>{{ article.ressort.name }} | von {{ article.author }}</h5>

            <p class="text-justify">
                {% for word in article.get_teaser %}
                    {{ word }}
                {% endfor %}
            </p>
        {% empty %}
            <div class="container">
                <h3>Unfortunately no articles yet</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/keineartikel.html
<div class="container">
    <h4>Es tut uns sehr leid!</h4>
    <p>Es sind noch keine Artikel für dieses Ressort verfügbar.</p>
</div>

templates/landing.html
{% extends "base.html" %}

{% block header %}
    <header class="sb-page-header">
        <div class="container">
            <h1>Essenz</h1>

            <p>Nachrichten - kurz und bündig.</p>
        </div>

    </header>
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {##}
    {#        <h1>TROLOLO</h1>#}
    {#    </div>#}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-7">
            {% for article in article_list %}
                {% if forloop.counter != 1 %}
                    <hr>
                {% endif %}
                <h2><a href="{{ article.ressort.slug }}/{{ article.slug }}">{{ article.title }}</a></h2>
                <h4>{{ article.ressort.name }} | von {{ article.author }}</h4>

                <p class="text-justify">
                    {% for word in article.get_teaser %}
                        {{ word }}
                    {% endfor %}
                </p>
            {% empty %}
                <div class="container">
                    <h3>Unfortunately no articles yet</h3>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="/cars?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="/cars?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">Schwerpunkte</h1>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        {% for article in schwerpunkt_list %}
                            <a href="{{ article.ressort.slug }}/{{ article.slug }}" class="list-group-item">
                                <span class="badge">{{ article.category }}</span>
                                {{ article.title }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href={% url "landing" %}>Home</a>
        </div>

        <div class="navbar-collapse collapse" id="navigationbar">
            <ul class="nav navbar-nav">

                <li><a href={% url "ressort" "inland" %}>Inland</a></li>
                <li><a href={% url "ressort" "international" %}>International</a></li>
                <li><a href={% url "ressort" "chronik" %}>Chronik</a></li>
                <li><a href={% url "ressort" "wirtschaft" %}>Wirtschaft</a></li>
                <li><a href={% url "ressort" "sport" %}>Sport</a></li>
                <li><a href={% url "ressort" "schwerpunkt" %}>Schwerpunkt</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
{#                    <button type="button" class="btn btn-default navbar-btn">#}
                        <a href={% url "lexikon_base" %}>Was ist was?</a>
{#                    </button>#}
                </li>
                <li><a href={% url "aboutus" %}>Über uns</a></li>
            </ul>

            {#            <div id="navbar" class="navbar-collapse collapse">#}
            {#                <form class="navbar-form navbar-right">#}
            {#                    <div class="form-group">#}
            {#                        <input type="text" placeholder="Email" class="form-control">#}
            {#                    </div>#}
            {#                    <div class="form-group">#}
            {#                        <input type="password" placeholder="Password" class="form-control">#}
            {#                    </div>#}
            {#                    <button type="submit" class="btn btn-success">Sign in</button>#}
            {#                </form>#}
            {#            </div>#}
        </div>

    </div>
</nav>

templates/ressort.html
{% extends "base.html" %}

{% block title %}
    {{ ressort.name }}
{% endblock %}

{% block header %}
    <header class="sb-page-header">
        <div class="container">
            <h1>Essenz</h1>

            <p>{{ ressort.name }}</p>
        </div>

    </header>
{% endblock %}

{% block jumbotron %}
    {#    <div class="jumbotron">#}
    {#        <div class="container">#}
    {#            <h1>#}
    {#                {{ ressort.name }}#}
    {#            </h1>#}
    {##}
    {#            <p>#}
    {#                {{ ressort.subtitle }}#}
    {#            </p>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1>{{ ressort.article_list }}</h1>
            {% for article in ressort.article_set.all %}
                {% if forloop.counter != 1 %}
                    <hr>
                {% endif %}

                <h2><a href={{ article.slug }}>{{ article.title }}</a></h2>
                <h4>Von {{ article.author }} | {{ article.created }}</h4>

                <p class="text-justify">
                    {% for word in article.get_teaser %}
                        {{ word }}
                    {% endfor %}
                </p>
            {% empty %}
                {% include 'keineartikel.html' %}
            {% endfor %}
        </div>
        <div class="col-md-4">

        </div>
    </div>
{% endblock %}

templates/wasistwas_header.html
<header class="sb-page-header-lex">
    <div class="container">
        <h1>Essenz</h1>

        <p>Was ist was? - Essentielles leicht erklärt.</p>
    </div>
</header>